name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  TERRAFORM_VERSION: 1.4.0
  TERRAGRUNT_VERSION: 0.44.4

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          wget https://releases.hashicorp.com/terraform/${{ env.TERRAFORM_VERSION }}/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${{ env.TERRAGRUNT_VERSION }}/terragrunt_linux_amd64

          sudo unzip terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip -d /usr/local/bin
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Init terragrunt
        run: |
          terragrunt init
          terragrunt fmt
          terragrunt run-all validate
          terragrunt validate-inputs --terragrunt-strict-validate

  generate_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get install pandoc/jammy

          curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mv terraform-docs /usr/local/bin

      - name: Generate docs
        run: |
          terraform-docs markdown table modules/k3s-cluster --output-file ../../docs/02_terraform_module.md
          pandoc -s $(cat includes.txt) --quiet -f gfm -t html5 -o RESULT.md
